### ISSUE TITLE
The parameter "robots_txt" must be defined.  

### ISSUE THREAD

**Issue by AlexSmok** [evheniy/RobotsTxtBundle#1]
На app/console robots.txt:dump --env=prod 
получаю
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "robots_txt" must be defined.  

app/console robots.txt:dump --env=dev 
и app/console robots.txt:dump отрабатывают нормально

правил config.yml

**Comment by evheniy** [comment]
Привет
Попробуй для prod сделать правки в файле app/config/config_prod.yml (добавить конфиг robots_txt)
Если окружение разделять не надо (prod, dev...), тогда можно сделать один конфиг в файле app/config/config.yml.
Но, если нужно, тогда в этом файле не нужно указывать конфиги, нужно отдельно делать конфиг для prod - app/config/config_prod.yml. А для dev - app/config/config_dev.yml. В app/config/config.yml ничего добавлять не нужно.
